add AWS::APS::Workspace without tagging

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -2,28 +2,47 @@ version: 0.2
 phases:
   install:
     runtime-versions:
-        java: openjdk8
-        python: 3.7
+      python: 3.7
+      golang: 1.13
     commands:
-      -  pip install pre-commit cloudformation-cli-java-plugin
+      - pip install -U 'six~=1.15'
+      - pip install -U 'pyyaml~=5.4'
+      - pip install -U pre-commit cloudformation-cli-go-plugin
   build:
     commands:
       - pre-commit run --all-files
       - |
         if [ "$(ls -A $CODEBUILD_SRC_DIR)" ]; then
           cd $CODEBUILD_SRC_DIR
-          # skip hidden folders
-          dirs=$(find . -not -path "\./\.*" -mindepth 1 -maxdepth 1 -type d)
-          echo "Folders to build: $dirs"
-          for directory in $dirs; do
+
+          for directory in aws-aps-workspace; do
             cd "$directory"
-            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
+
+            cfn generate
             if [ "$?" -ne 0 ] ; then
-                echo "Build failed!"
+                echo "cfn generate failed!"
                 exit 1
-            else
-                cd ".."
             fi
+
+            go get ./...
+            if [ "$?" -ne 0 ] ; then
+                echo "go get failed!"
+                exit 1
+            fi
+
+            go test ./...
+            if [ "$?" -ne 0 ] ; then
+                echo "go test failed!"
+                exit 1
+            fi
+            make -f makebuild build
+
+            if [ "$?" -ne 0 ] ; then
+                echo "go build failed!"
+                exit 1
+            fi
+
+            cd ..
           done
         else
           echo "$CODEBUILD_SRC_DIR is empty"
